/*
 * SystemException.h
 *
 * Exceptions and errors generated by system calls
 *
 *
 * Copyright (C) 2018 Amit Kumar (amitkriit@gmail.com)
 * This program is part of the Wanhive IoT Platform.
 * Check the COPYING file for the license.
 *
 */

#ifndef WH_BASE_SYSTEMEXCEPTION_H_
#define WH_BASE_SYSTEMEXCEPTION_H_
#include "common/BaseException.h"

namespace wanhive {
/**
 * Exceptions generate by system calls
 */
class SystemException: public BaseException {
public:
	SystemException() noexcept;
	SystemException(int type) noexcept;
	virtual ~SystemException() override;
	const char* what() const noexcept override;
	int errorCode() const noexcept override;
private:
	//Should be sufficient
	static constexpr int MSG_LEN = 256;

	int error;
	char buffer[MSG_LEN];
};

} /* namespace wanhive */

#endif /* WH_BASE_SYSTEMEXCEPTION_H_ */
