/*
 * SystemException.cpp
 *
 * Exceptions and errors generated by system calls
 *
 *
 * Copyright (C) 2018 Amit Kumar (amitkriit@gmail.com)
 * This program is part of the Wanhive IoT Platform.
 * Check the COPYING file for the license.
 *
 */

#include "SystemException.h"
#include <cerrno>
#include <cstring>

namespace wanhive {

SystemException::SystemException() noexcept {
	error = errno;
}

SystemException::SystemException(int type) noexcept {
	error = type;
}

SystemException::~SystemException() {

}

const char* SystemException::what() const noexcept {
	/* Check whether XSI compliant STRERROR is available */
#if (_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600) && ! _GNU_SOURCE
	buffer[0]='\0';
	strerror_r(error, (char *) buffer, MSG_LEN);
	return buffer;
#else
	return strerror_r(error, (char*) buffer, MSG_LEN);
#endif
}

int SystemException::errorCode() const noexcept {
	return this->error;
}

} /* namespace wanhive */
